export type DemandLevel = 'Rare' | 'Competitive' | 'Oversaturated';

export interface Skill {
  name: string;
  covered: boolean; // user has it from their courses
}

export interface Job {
  id: string;
  title: string;
  company: string;
  salaryMin: number;
  salaryMax: number;
  demand: DemandLevel;
  skillsRequired: string[];
  skillsUser: string[]; // skills the user has from their selected courses
  typeFit: string[]; // 4-letter archetypes that match well
  field: string;
  description: string;
}

export const jobs: Job[] = [
  {
    id: 'ds-shopee',
    title: 'Marketplace Recommendation Data Scientist',
    company: 'Shopee',
    salaryMin: 8000,
    salaryMax: 14000,
    demand: 'Rare',
    skillsRequired: ['Python', 'SQL', 'Statistics', 'Machine Learning', 'Data Visualization'],
    skillsUser: ['Data Science', 'Machine Learning', 'Data Structures & Algorithms', 'Statistics & Probability', 'Linear Algebra'],
    typeFit: ['SECT', 'SEST', 'BSCT', 'SEGT'],
    field: 'Data Science',
    description: 'Build recommendation models and data pipelines at one of Southeast Asia\'s largest e-commerce platforms.',
  },
  {
    id: 'be-grab',
    title: 'Backend Payments Platform Engineer',
    company: 'Grab',
    salaryMin: 7000,
    salaryMax: 13000,
    demand: 'Competitive',
    skillsRequired: ['Python', 'APIs', 'Databases', 'Microservices', 'Redis'],
    skillsUser: ['Database Management Systems', 'Object-Oriented Programming', 'Web Development', 'Data Structures & Algorithms'],
    typeFit: ['BECT', 'BEST', 'BSST', 'BEGT'],
    field: 'Software Engineering',
    description: 'Build and scale the APIs powering Grab\'s super-app across 8 countries.',
  },
  {
    id: 'csa-maxis',
    title: 'SOC Incident Response Analyst',
    company: 'Maxis',
    salaryMin: 6000,
    salaryMax: 11000,
    demand: 'Rare',
    skillsRequired: ['Network Security', 'Linux', 'Penetration Testing', 'SIEM', 'Incident Response'],
    skillsUser: ['Computer Networks', 'Operating Systems', 'Information Security', 'Cybersecurity'],
    typeFit: ['BSST', 'BSSD', 'SSST', 'SSGT'],
    field: 'Cybersecurity',
    description: 'Protect Maxis\' enterprise network and respond to security incidents across Malaysia\'s telecom infrastructure.',
  },
  {
    id: 'fs-carsome',
    title: 'Full-Stack E-Commerce Platform Developer',
    company: 'Carsome',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['React', 'Node.js', 'SQL', 'TypeScript', 'Git'],
    skillsUser: ['Web Development', 'Object-Oriented Programming', 'Database Management Systems', 'Software Engineering'],
    typeFit: ['BEGT', 'BECT', 'BSST', 'BEST'],
    field: 'Software Engineering',
    description: 'Build features for Malaysia\'s largest car e-commerce platform — from listing to financing.',
  },
  {
    id: 'pm-airasia',
    title: 'Digital Travel Product Manager',
    company: 'AirAsia',
    salaryMin: 8000,
    salaryMax: 15000,
    demand: 'Competitive',
    skillsRequired: ['Product Strategy', 'Data Analysis', 'Stakeholder Management', 'Roadmapping', 'A/B Testing'],
    skillsUser: ['Data Science', 'Machine Learning', 'UX Design', 'Product Management'],
    typeFit: ['SEGT', 'SSGT', 'SESD', 'SSCT'],
    field: 'Product Management',
    description: 'Drive the digital product roadmap for AirAsia\'s Super App used by millions across Asia.',
  },
  {
    id: 'mle-nvidia',
    title: 'GPU Machine Learning Engineer',
    company: 'NVIDIA',
    salaryMin: 10000,
    salaryMax: 18000,
    demand: 'Rare',
    skillsRequired: ['Python', 'Deep Learning', 'MLOps', 'PyTorch', 'GPU Computing'],
    skillsUser: ['Machine Learning', 'Artificial Intelligence', 'Python (assumed)', 'Linear Algebra', 'Statistics & Probability'],
    typeFit: ['BSCT', 'SEST', 'BEST', 'SECT'],
    field: 'AI / Machine Learning',
    description: 'Build and optimize ML training pipelines for NVIDIA\'s AI research team in Malaysia.',
  },
  {
    id: 'devaelio',
    title: 'Cloud DevOps Automation Engineer',
    company: 'aelio',
    salaryMin: 7000,
    salaryMax: 13000,
    demand: 'Rare',
    skillsRequired: ['CI/CD', 'AWS', 'Docker', 'Kubernetes', 'Terraform'],
    skillsUser: ['Operating Systems', 'Computer Networks', 'Cloud Computing', 'Software Engineering'],
    typeFit: ['BSSD', 'BESD', 'BSST', 'BSGT'],
    field: 'DevOps',
    description: 'Build and maintain CI/CD pipelines and cloud infrastructure for a managed cloud services provider.',
  },
  {
    id: 'ba-maybank',
    title: 'Core Banking Business Systems Analyst',
    company: 'Maybank',
    salaryMin: 5500,
    salaryMax: 10000,
    demand: 'Competitive',
    skillsRequired: ['SQL', 'Excel', 'Business Processes', 'Requirements Gathering', 'Data Analysis'],
    skillsUser: ['Database Management Systems', 'Data Science', 'Statistics & Probability'],
    typeFit: ['SSGT', 'SESD', 'SEGT', 'SSCT'],
    field: 'Business Analysis',
    description: 'Bridge business and technology teams at Malaysia\'s largest bank, translating requirements into solutions.',
  },
  {
    id: 'aie-jd',
    title: 'LLM Application Engineer',
    company: 'JD.com Malaysia',
    salaryMin: 9000,
    salaryMax: 16000,
    demand: 'Rare',
    skillsRequired: ['Python', 'LLMs', 'RAG', 'ML Engineering', 'API Integration'],
    skillsUser: ['Artificial Intelligence', 'Machine Learning', 'Web Development', 'Natural Language Processing'],
    typeFit: ['BSCT', 'BSGT', 'SECT', 'BEST'],
    field: 'AI / Machine Learning',
    description: 'Build LLM-powered products for JD\'s Southeast Asian e-commerce and logistics operations.',
  },
  {
    id: 'sa-aws',
    title: 'Enterprise Cloud Solutions Architect',
    company: 'AWS Malaysia',
    salaryMin: 12000,
    salaryMax: 20000,
    demand: 'Rare',
    skillsRequired: ['Cloud Architecture', 'AWS', 'Networking', 'Security', 'Cost Optimization'],
    skillsUser: ['Cloud Computing', 'Computer Networks', 'Operating Systems', 'Distributed Systems'],
    typeFit: ['BSGT', 'BSST', 'BESD', 'BEST'],
    field: 'Cloud Engineering',
    description: 'Design large-scale cloud architectures for Malaysian enterprises migrating to AWS.',
  },
  {
    id: 'sre-shopee',
    title: 'Site Reliability Engineer, Checkout Platform',
    company: 'Shopee',
    salaryMin: 7500,
    salaryMax: 14000,
    demand: 'Rare',
    skillsRequired: ['Linux', 'Monitoring', 'Python', 'Incident Response', 'Automation'],
    skillsUser: ['Operating Systems', 'Object-Oriented Programming', 'Cloud Computing', 'Data Structures & Algorithms'],
    typeFit: ['BESD', 'BSSD', 'BSST', 'BECT'],
    field: 'DevOps',
    description: 'Keep Shopee\'s platform running at 99.99% uptime — from alerts to post-mortems.',
  },
  {
    id: 'de-petronas',
    title: 'Energy Data Platform Engineer',
    company: 'Petronas Digital',
    salaryMin: 8000,
    salaryMax: 15000,
    demand: 'Rare',
    skillsRequired: ['SQL', 'Apache Spark', 'Python', 'Data Pipelines', 'Airflow'],
    skillsUser: ['Database Management Systems', 'Data Science', 'Distributed Systems', 'Cloud Computing'],
    typeFit: ['SEST', 'BSGT', 'BSST', 'SECT'],
    field: 'Data Science',
    description: 'Build petabyte-scale data pipelines powering Petronas\'s digital transformation.',
  },
  {
    id: 'uxr-bankislam',
    title: 'Digital Banking UX Researcher',
    company: 'Bank Islam',
    salaryMin: 5000,
    salaryMax: 9000,
    demand: 'Competitive',
    skillsRequired: ['User Research', 'Figma', 'Usability Testing', 'Journey Mapping', 'Synthesis'],
    skillsUser: ['Human-Computer Interaction', 'UX Design', 'Data Science'],
    typeFit: ['SSCT', 'SSCD', 'SEGT', 'SSST'],
    field: 'UI/UX Design',
    description: 'Conduct research to improve digital banking experiences for Malaysia\'s Islamic finance customers.',
  },
  {
    id: 'tw-mdec',
    title: 'API Documentation Specialist',
    company: 'MDEC',
    salaryMin: 4500,
    salaryMax: 8000,
    demand: 'Competitive',
    skillsRequired: ['Technical Writing', 'API Documentation', 'Markdown', 'Developer Tools', 'Clarity'],
    skillsUser: ['Web Development', 'Software Engineering'],
    typeFit: ['SSST', 'SSGT', 'SSCT', 'SSCD'],
    field: 'Technical Writing',
    description: 'Write developer documentation and API references for Malaysia\'s tech ecosystem initiatives.',
  },
  {
    id: 'oa-dhl',
    title: 'Logistics Operations Data Analyst',
    company: 'DHL Express Malaysia',
    salaryMin: 5000,
    salaryMax: 9000,
    demand: 'Competitive',
    skillsRequired: ['Excel', 'SQL', 'Process Optimization', 'Reporting', 'Logistics Basics'],
    skillsUser: ['Database Management Systems', 'Statistics & Probability', 'Data Science'],
    typeFit: ['SESD', 'SSGT', 'SEGT', 'SEST'],
    field: 'Business Analysis',
    description: 'Optimise logistics operations across Malaysia using data — from route efficiency to inventory forecasting.',
  },
  {
    id: 'md-tng',
    title: 'Mobile Wallet Engineer',
    company: 'Touch \'n Go Digital',
    salaryMin: 6000,
    salaryMax: 11000,
    demand: 'Competitive',
    skillsRequired: ['Flutter', 'React Native', 'iOS', 'Android', 'REST APIs'],
    skillsUser: ['Mobile App Development', 'Object-Oriented Programming', 'Web Development', 'Database Management Systems'],
    typeFit: ['BEGT', 'BECT', 'BSST', 'BEST'],
    field: 'Mobile Development',
    description: 'Build the mobile app used daily by millions of Malaysians for payments and transit.',
  },
  {
    id: 'fe-setel',
    title: 'Frontend Design Systems Engineer',
    company: 'Setel',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['React', 'TypeScript', 'Design Systems', 'Accessibility', 'REST APIs'],
    skillsUser: ['Web Development', 'Human-Computer Interaction', 'Software Engineering', 'Object-Oriented Programming'],
    typeFit: ['BEGT', 'BECT', 'SSCT', 'BEST'],
    field: 'Software Engineering',
    description: 'Build reusable product UI components for Setel\'s payments and mobility platform.',
  },
  {
    id: 'pt-securemetric',
    title: 'Web Application Penetration Tester',
    company: 'Securemetric',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Rare',
    skillsRequired: ['Penetration Testing', 'Network Security', 'Linux', 'OWASP', 'Reporting'],
    skillsUser: ['Information Security', 'Cybersecurity', 'Computer Networks', 'Operating Systems'],
    typeFit: ['BSST', 'BSSD', 'SSST', 'SSGT'],
    field: 'Cybersecurity',
    description: 'Test web applications and produce clear remediation reports for enterprise clients.',
  },
  {
    id: 'cyber-analyst-celcomdigi',
    title: 'Cybersecurity Analyst',
    company: 'CelcomDigi',
    salaryMin: 5500,
    salaryMax: 9500,
    demand: 'Competitive',
    skillsRequired: ['Network Security', 'SIEM', 'Vulnerability Assessment', 'Linux', 'Reporting'],
    skillsUser: ['Computer Networks', 'Information Security', 'Cybersecurity', 'Operating Systems'],
    typeFit: ['BSST', 'BSSD', 'SSST', 'SSGT'],
    field: 'Cybersecurity',
    description: 'Monitor security posture, triage vulnerabilities, and support remediation across telecom systems.',
  },
  {
    id: 'soc-analyst-time',
    title: 'SOC Analyst (Security Operations Center Analyst)',
    company: 'Time dotCom',
    salaryMin: 4500,
    salaryMax: 8500,
    demand: 'Competitive',
    skillsRequired: ['SIEM', 'Incident Response', 'Security Monitoring', 'Network Security', 'Linux'],
    skillsUser: ['Computer Networks', 'Operating Systems', 'Information Security', 'Cybersecurity'],
    typeFit: ['BSST', 'BSSD', 'SSST', 'SSGT'],
    field: 'Cybersecurity',
    description: 'Watch alerts, investigate suspicious activity, and escalate incidents from the SOC floor.',
  },
  {
    id: 'isa-maybank',
    title: 'Information Security Analyst',
    company: 'Maybank',
    salaryMin: 6000,
    salaryMax: 10500,
    demand: 'Rare',
    skillsRequired: ['Risk Assessment', 'Compliance', 'Security Policies', 'SIEM', 'Incident Response'],
    skillsUser: ['Information Security', 'Cybersecurity', 'Computer Networks', 'Operating Systems'],
    typeFit: ['BSST', 'BSSD', 'SSGT', 'SSST'],
    field: 'Cybersecurity',
    description: 'Review security controls, support audits, and help banking teams meet security requirements.',
  },
  {
    id: 'itsec-sunway',
    title: 'IT Security Specialist',
    company: 'Sunway Digital',
    salaryMin: 5200,
    salaryMax: 9000,
    demand: 'Competitive',
    skillsRequired: ['Endpoint Security', 'Identity Access Management', 'Network Security', 'Firewall', 'Reporting'],
    skillsUser: ['Computer Networks', 'Operating Systems', 'Information Security'],
    typeFit: ['BSST', 'BSSD', 'BESD', 'SSGT'],
    field: 'Cybersecurity',
    description: 'Maintain endpoint protection, access controls, and security tooling for enterprise IT teams.',
  },
  {
    id: 'jr-pentest-lgms',
    title: 'Junior Penetration Tester',
    company: 'LGMS',
    salaryMin: 4200,
    salaryMax: 8000,
    demand: 'Rare',
    skillsRequired: ['Penetration Testing', 'OWASP', 'Linux', 'Network Security', 'Reporting'],
    skillsUser: ['Information Security', 'Cybersecurity', 'Computer Networks', 'Operating Systems'],
    typeFit: ['BSST', 'BSSD', 'SSST', 'BECT'],
    field: 'Cybersecurity',
    description: 'Assist security consultants with web, network, and infrastructure penetration testing engagements.',
  },
  {
    id: 'cse-cimb',
    title: 'Cloud Security Engineer',
    company: 'CIMB Digital Assets',
    salaryMin: 8500,
    salaryMax: 15000,
    demand: 'Rare',
    skillsRequired: ['Cloud Architecture', 'AWS', 'Security', 'SIEM', 'Incident Response'],
    skillsUser: ['Cloud Computing', 'Computer Networks', 'Information Security', 'Operating Systems'],
    typeFit: ['BSST', 'BSSD', 'BESD', 'BSGT'],
    field: 'Cloud Engineering',
    description: 'Harden cloud workloads, monitor threats, and improve security controls for digital banking systems.',
  },
  {
    id: 'bi-tm',
    title: 'Power BI Analytics Developer',
    company: 'TM Digital',
    salaryMin: 5500,
    salaryMax: 9500,
    demand: 'Competitive',
    skillsRequired: ['SQL', 'Power BI', 'Data Visualization', 'Data Analysis', 'Excel'],
    skillsUser: ['Database Management Systems', 'Data Science', 'Statistics & Probability'],
    typeFit: ['SEST', 'SESD', 'SSGT', 'SEGP'],
    field: 'Data Science',
    description: 'Create executive dashboards and self-service analytics for telco product and operations teams.',
  },
  {
    id: 'mlops-boost',
    title: 'MLOps Platform Engineer',
    company: 'Boost Bank',
    salaryMin: 9000,
    salaryMax: 16000,
    demand: 'Rare',
    skillsRequired: ['MLOps', 'Python', 'Docker', 'Kubernetes', 'Monitoring'],
    skillsUser: ['Machine Learning', 'Cloud Computing', 'Operating Systems', 'Software Engineering'],
    typeFit: ['BSCT', 'SEST', 'BESD', 'BSGT'],
    field: 'AI / Machine Learning',
    description: 'Ship and monitor ML models for digital banking risk, growth, and personalization use cases.',
  },
  {
    id: 'tpd-govtech',
    title: 'Technical Product Owner',
    company: 'MYDigital',
    salaryMin: 7500,
    salaryMax: 13000,
    demand: 'Competitive',
    skillsRequired: ['Product Strategy', 'Requirements Gathering', 'Stakeholder Management', 'APIs', 'Roadmapping'],
    skillsUser: ['Product Management', 'Software Engineering', 'Data Science', 'Human-Computer Interaction'],
    typeFit: ['SEGT', 'SSGT', 'SESD', 'BEGT'],
    field: 'Product Management',
    description: 'Translate public-sector digital service needs into clear delivery backlogs for engineering teams.',
  },
  {
    id: 'uxd-foodpanda',
    title: 'Food Delivery Product Designer',
    company: 'foodpanda Malaysia',
    salaryMin: 6000,
    salaryMax: 11000,
    demand: 'Competitive',
    skillsRequired: ['Figma', 'User Research', 'Prototyping', 'Usability Testing', 'Journey Mapping'],
    skillsUser: ['UX Design', 'Human-Computer Interaction', 'Web Development'],
    typeFit: ['SSCT', 'SSCD', 'SEGT', 'SSST'],
    field: 'UI/UX Design',
    description: 'Design ordering, rider, and merchant flows across foodpanda\'s Malaysian marketplace.',
  },
  {
    id: 'gtools-lemonsky',
    title: 'Game Tools Programmer',
    company: 'Lemon Sky Studios',
    salaryMin: 5500,
    salaryMax: 10000,
    demand: 'Competitive',
    skillsRequired: ['C++', 'Python', 'Graphics', 'OOP', 'Tooling'],
    skillsUser: ['Object-Oriented Programming', 'Data Structures & Algorithms', 'Software Engineering'],
    typeFit: ['BECT', 'BEGT', 'BEST', 'BSCT'],
    field: 'Game Development',
    description: 'Build internal tools that help artists and developers produce game assets more efficiently.',
  },
  {
    id: 'devrel-mongodb',
    title: 'Developer Documentation Engineer',
    company: 'MongoDB Malaysia',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Rare',
    skillsRequired: ['API Documentation', 'Markdown', 'Developer Tools', 'JavaScript', 'Clarity'],
    skillsUser: ['Web Development', 'Software Engineering', 'Database Management Systems'],
    typeFit: ['SSST', 'SSGT', 'SSCD', 'BECT'],
    field: 'Technical Writing',
    description: 'Create hands-on database guides and developer tutorials for Southeast Asian engineering teams.',
  },
  {
    id: 'android-rhb',
    title: 'Android Banking App Engineer',
    company: 'RHB Banking Group',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['Android', 'Kotlin', 'REST APIs', 'Security', 'Git'],
    skillsUser: ['Mobile App Development', 'Object-Oriented Programming', 'Computer Networks', 'Software Engineering'],
    typeFit: ['BEGT', 'BECT', 'BSST', 'BEST'],
    field: 'Mobile Development',
    description: 'Develop secure Android banking features used by retail customers across Malaysia.',
  },
  {
    id: 'fe-perf-airasia',
    title: 'Frontend Performance Engineer',
    company: 'AirAsia Tech',
    salaryMin: 8000,
    salaryMax: 14000,
    demand: 'Competitive',
    skillsRequired: ['Web Performance', 'Lighthouse', 'React', 'CDN', 'Profiling'],
    skillsUser: ['Web Development', 'Performance Engineering', 'JavaScript', 'Software Engineering'],
    typeFit: ['BEGT', 'BECT', 'BSST'],
    field: 'Software Engineering',
    description: 'Optimize critical rendering paths, bundle sizes and runtime performance for high-traffic web apps.',
  },
  {
    id: 'nlp-research-xyz',
    title: 'NLP Research Engineer (R&D)',
    company: 'Local AI Lab',
    salaryMin: 10000,
    salaryMax: 18000,
    demand: 'Rare',
    skillsRequired: ['Natural Language Processing', 'PyTorch', 'Transformers', 'Research', 'Python'],
    skillsUser: ['Artificial Intelligence', 'Machine Learning', 'Natural Language Processing', 'Statistics & Probability'],
    typeFit: ['BSCT', 'SECT', 'BEST'],
    field: 'AI / Machine Learning',
    description: 'Research and prototype novel NLP models for low-resource Southeast Asian languages.',
  },
  {
    id: 'stream-de-dataflow',
    title: 'Streaming Data Engineer (Kafka/Spark)',
    company: 'FinTech Scaleup',
    salaryMin: 9000,
    salaryMax: 15000,
    demand: 'Rare',
    skillsRequired: ['Kafka', 'Spark', 'Streaming ETL', 'Python/Scala', 'Monitoring'],
    skillsUser: ['Distributed Systems', 'Database Management Systems', 'Cloud Computing', 'Data Science'],
    typeFit: ['SEST', 'BSGT', 'BSCT'],
    field: 'Data Engineering',
    description: 'Design low-latency streaming pipelines powering real-time analytics and fraud detection.',
  },
  {
    id: 'mobile-sec-engineer',
    title: 'Mobile Security Engineer',
    company: 'Payments Provider',
    salaryMin: 8500,
    salaryMax: 14000,
    demand: 'Competitive',
    skillsRequired: ['Mobile Security', 'Static Analysis', 'Runtime Protections', 'iOS/Android', 'Reverse Engineering'],
    skillsUser: ['Mobile App Development', 'Information Security', 'Operating Systems', 'Computer Networks'],
    typeFit: ['BSST', 'BSSD', 'BEGT'],
    field: 'Cybersecurity',
    description: 'Harden mobile wallet apps against client-side attacks and ensure secure key management.',
  },
  {
    id: 'platform-sec-fw',
    title: 'Platform Security Engineer (Cloud Infra)',
    company: 'Regional Cloud',
    salaryMin: 11000,
    salaryMax: 19000,
    demand: 'Rare',
    skillsRequired: ['Cloud Security', 'Kubernetes', 'IAM', 'Threat Modeling', 'SIEM'],
    skillsUser: ['Cloud Computing', 'Information Security', 'Computer Networks', 'Distributed Systems'],
    typeFit: ['BSGT', 'BESD', 'BSSD'],
    field: 'Cloud Engineering',
    description: 'Secure multi-tenant cloud platforms, perform threat hunts and build platform hardening automation.',
  },
  {
    id: 'fw-embedded-iot',
    title: 'Embedded Firmware Engineer (IoT)',
    company: 'Hardware Startup',
    salaryMin: 7000,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['C', 'RTOS', 'Embedded Linux', 'Hardware Debugging', 'IoT Protocols'],
    skillsUser: ['Computer Architecture', 'Operating Systems', 'Embedded Systems', 'Electronics'],
    typeFit: ['BECT', 'BEGT', 'BSCT'],
    field: 'Embedded Systems',
    description: 'Develop low-power firmware for connected sensors and perform hardware-in-the-loop testing.',
  },
  {
    id: 'product-analytics-lead',
    title: 'Product Analytics Manager (Growth)',
    company: 'Regional Marketplace',
    salaryMin: 9000,
    salaryMax: 16000,
    demand: 'Competitive',
    skillsRequired: ['Experimentation', 'SQL', 'Analytics', 'Cohort Analysis', 'Dashboarding'],
    skillsUser: ['Data Science', 'Statistics & Probability', 'Database Management Systems', 'Product Management'],
    typeFit: ['SEGT', 'SESD', 'SSGT'],
    field: 'Data Science',
    description: 'Lead A/B testing programs and metrics to drive user growth and retention across product funnels.',
  },
  // ── Additional Malaysian Companies ──
  {
    id: 'be-grab-food',
    title: 'Backend Engineer, Food Delivery Platform',
    company: 'Grab',
    salaryMin: 7500,
    salaryMax: 14000,
    demand: 'Competitive',
    skillsRequired: ['Java', 'Microservices', 'Kafka', 'PostgreSQL', 'Redis'],
    skillsUser: ['Database Management Systems', 'Object-Oriented Programming', 'Software Engineering', 'Data Structures & Algorithms'],
    typeFit: ['BECT', 'BEST', 'BSST', 'BEGT'],
    field: 'Software Engineering',
    description: 'Build high-throughput APIs powering GrabFood delivery across Southeast Asia.',
  },
  {
    id: 'ds-shopee-rec',
    title: 'Recommendation Systems Data Scientist',
    company: 'Shopee',
    salaryMin: 8500,
    salaryMax: 15000,
    demand: 'Rare',
    skillsRequired: ['Python', 'SQL', 'Machine Learning', 'Recommendation Systems', 'Spark'],
    skillsUser: ['Data Science', 'Machine Learning', 'Statistics & Probability', 'Linear Algebra'],
    typeFit: ['SECT', 'SEST', 'BSCT', 'SEGT'],
    field: 'Data Science',
    description: 'Develop personalisation and recommendation models to improve user discovery on Shopee.',
  },
  {
    id: 'fe-carsome',
    title: 'Frontend Engineer, Buyer Experience',
    company: 'Carsome',
    salaryMin: 6000,
    salaryMax: 11000,
    demand: 'Competitive',
    skillsRequired: ['React', 'TypeScript', 'CSS', 'Jest', 'REST APIs'],
    skillsUser: ['Web Development', 'Object-Oriented Programming', 'Software Engineering'],
    typeFit: ['BEGT', 'BECT', 'SSCT', 'BEST'],
    field: 'Software Engineering',
    description: 'Build intuitive car buying experiences for Malaysian consumers on Carsome\'s web platform.',
  },
  {
    id: 'cloud-cimb',
    title: 'Cloud Infrastructure Engineer',
    company: 'CIMB',
    salaryMin: 7500,
    salaryMax: 13500,
    demand: 'Competitive',
    skillsRequired: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'Linux'],
    skillsUser: ['Cloud Computing', 'Operating Systems', 'Computer Networks', 'Distributed Systems'],
    typeFit: ['BSGT', 'BSST', 'BESD', 'BEST'],
    field: 'Cloud Engineering',
    description: 'Maintain and scale cloud infrastructure for Malaysia\'s leading investment bank.',
  },
  {
    id: 'pm-touch-n-go',
    title: 'Product Manager, Super App',
    company: 'Touch \'n Go Digital',
    salaryMin: 8500,
    salaryMax: 15000,
    demand: 'Competitive',
    skillsRequired: ['Product Strategy', 'Data Analysis', 'Roadmapping', 'Stakeholder Management', 'A/B Testing'],
    skillsUser: ['Product Management', 'Data Science', 'UX Design'],
    typeFit: ['SEGT', 'SSGT', 'SESD', 'SSCT'],
    field: 'Product Management',
    description: 'Drive the product roadmap for TNG Digital\'s e-wallet and mobility super app.',
  },
  {
    id: 'ml-celcomdigi',
    title: 'Telco Data Scientist',
    company: 'CelcomDigi',
    salaryMin: 7000,
    salaryMax: 13000,
    demand: 'Rare',
    skillsRequired: ['Python', 'Predictive Analytics', 'Network Optimization', 'SQL', 'ML Engineering'],
    skillsUser: ['Data Science', 'Machine Learning', 'Statistics & Probability', 'Database Management Systems'],
    typeFit: ['SEST', 'BSCT', 'BSGT', 'SEGT'],
    field: 'Data Science',
    description: 'Apply machine learning to optimise network quality and customer experience for CelcomDigi.',
  },
  {
    id: 'mobile-lalamove',
    title: 'Flutter Mobile Engineer',
    company: 'Lalamove',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['Flutter', 'Dart', 'iOS', 'Android', 'Firebase'],
    skillsUser: ['Mobile App Development', 'Object-Oriented Programming', 'Software Engineering'],
    typeFit: ['BEGT', 'BECT', 'BSST', 'BEST'],
    field: 'Mobile Development',
    description: 'Build the driver and sender mobile apps powering same-day logistics across Malaysia.',
  },
  {
    id: 'rev-entertainment',
    title: 'Full-Stack Engineer, Streaming Platform',
    company: 'REV Entertainment',
    salaryMin: 5500,
    salaryMax: 10000,
    demand: 'Competitive',
    skillsRequired: ['React', 'Node.js', 'PostgreSQL', 'AWS', 'TypeScript'],
    skillsUser: ['Web Development', 'Database Management Systems', 'Software Engineering', 'Object-Oriented Programming'],
    typeFit: ['BEGT', 'BECT', 'BEST', 'BSST'],
    field: 'Software Engineering',
    description: 'Build and scale streaming infrastructure for REV Entertainment\'s sports and entertainment platform.',
  },
  {
    id: 'rakuten-adtech',
    title: 'Programmatic Ads Engineer',
    company: 'Rakuten Malaysia',
    salaryMin: 6500,
    salaryMax: 11500,
    demand: 'Rare',
    skillsRequired: ['Python', 'SQL', 'Data Pipelines', 'RTB', 'Spark'],
    skillsUser: ['Data Science', 'Database Management Systems', 'Machine Learning', 'Statistics & Probability'],
    typeFit: ['SEST', 'BSGT', 'BSCT', 'BECT'],
    field: 'Data Engineering',
    description: 'Build real-time bidding pipelines powering Rakuten\'s advertising ecosystem in Malaysia.',
  },
  {
    id: 'propertyguru-ux',
    title: 'Senior UX Engineer',
    company: 'PropertyGuru',
    salaryMin: 8000,
    salaryMax: 14000,
    demand: 'Competitive',
    skillsRequired: ['Figma', 'Prototyping', 'HTML/CSS', 'User Research', 'Design Systems'],
    skillsUser: ['UX Design', 'Human-Computer Interaction', 'Web Development'],
    typeFit: ['SSCT', 'SSCD', 'SEGT', 'BEGT'],
    field: 'UI/UX Design',
    description: 'Bridge design and engineering to create world-class property search experiences.',
  },
  {
    id: 'mindvalley-backend',
    title: 'Backend Engineer, Learning Platform',
    company: 'Mindvalley',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['Python', 'Django', 'PostgreSQL', 'Redis', 'GraphQL'],
    skillsUser: ['Database Management Systems', 'Object-Oriented Programming', 'Web Development', 'Software Engineering'],
    typeFit: ['BECT', 'BEST', 'BSST', 'SEST'],
    field: 'Software Engineering',
    description: 'Build scalable backend services for Mindvalley\'s personal growth learning platform.',
  },
  {
    id: 'ninjavan-ops',
    title: 'Logistics Software Engineer',
    company: 'Ninjavan',
    salaryMin: 5500,
    salaryMax: 10000,
    demand: 'Competitive',
    skillsRequired: ['Java', 'Spring Boot', 'PostgreSQL', 'AWS', 'REST APIs'],
    skillsUser: ['Object-Oriented Programming', 'Database Management Systems', 'Software Engineering', 'Cloud Computing'],
    typeFit: ['BECT', 'BEST', 'BSST', 'BEGT'],
    field: 'Software Engineering',
    description: 'Develop parcel tracking and route optimisation systems for Ninjavan\'s logistics network.',
  },
  {
    id: 'mdec-devrel',
    title: 'Technical Community Manager',
    company: 'MDEC',
    salaryMin: 5000,
    salaryMax: 9000,
    demand: 'Competitive',
    skillsRequired: ['Technical Writing', 'Community Management', 'APIs', 'Events', 'Developer Tools'],
    skillsUser: ['Web Development', 'Software Engineering', 'Data Science'],
    typeFit: ['SSST', 'SSGT', 'SSCT', 'SEGT'],
    field: 'Technical Writing',
    description: 'Build and nurture Malaysia\'s developer community through events, docs, and outreach.',
  },
  {
    id: 'iprice-frontend',
    title: 'Frontend Engineer, Price Comparison',
    company: 'iPrice',
    salaryMin: 5000,
    salaryMax: 9500,
    demand: 'Competitive',
    skillsRequired: ['React', 'TypeScript', 'Next.js', 'SEO', 'Performance'],
    skillsUser: ['Web Development', 'Human-Computer Interaction', 'Software Engineering'],
    typeFit: ['BEGT', 'BECT', 'SSCT', 'BEST'],
    field: 'Software Engineering',
    description: 'Build fast, SEO-optimised pages for Malaysia\'s leading price comparison platform.',
  },
  {
    id: 'alibabacloud-sa',
    title: 'Cloud Solutions Architect',
    company: 'Alibaba Cloud Malaysia',
    salaryMin: 12000,
    salaryMax: 20000,
    demand: 'Rare',
    skillsRequired: ['Cloud Architecture', 'Alibaba Cloud', 'Networking', 'Security', 'Cost Optimization'],
    skillsUser: ['Cloud Computing', 'Computer Networks', 'Distributed Systems', 'Operating Systems'],
    typeFit: ['BSGT', 'BSST', 'BESD', 'BEST'],
    field: 'Cloud Engineering',
    description: 'Architect enterprise cloud solutions for Malaysian businesses on Alibaba Cloud.',
  },
  {
    id: 'boost-ml',
    title: 'ML Engineer, Financial Super App',
    company: 'Boost Bank',
    salaryMin: 9000,
    salaryMax: 16000,
    demand: 'Rare',
    skillsRequired: ['Python', 'MLOps', 'PyTorch', 'Feature Engineering', 'Model Serving'],
    skillsUser: ['Machine Learning', 'Artificial Intelligence', 'Statistics & Probability', 'Software Engineering'],
    typeFit: ['BSCT', 'SEST', 'BESD', 'BSGT'],
    field: 'AI / Machine Learning',
    description: 'Deploy and monitor production ML models for Boost\'s financial super app offerings.',
  },
  {
    id: 'hhc-crypto',
    title: 'Blockchain Security Engineer',
    company: 'H2H Crypto Malaysia',
    salaryMin: 8000,
    salaryMax: 15000,
    demand: 'Rare',
    skillsRequired: ['Smart Contracts', 'Solidity', 'Blockchain Security', 'Web3', 'Auditing'],
    skillsUser: ['Information Security', 'Cybersecurity', 'Object-Oriented Programming', 'Data Structures & Algorithms'],
    typeFit: ['BSST', 'BSSD', 'BECT', 'BSCT'],
    field: 'Cybersecurity',
    description: 'Audit and secure smart contracts and Web3 infrastructure for Malaysian crypto ventures.',
  },
  {
    id: 'kdi-digital',
    title: 'Digital Transformation Engineer',
    company: 'KDI Group',
    salaryMin: 6000,
    salaryMax: 11000,
    demand: 'Competitive',
    skillsRequired: ['SharePoint', 'Power Platform', 'Azure', 'Business Processes', 'Data Analysis'],
    skillsUser: ['Database Management Systems', 'Information Systems', 'Software Engineering'],
    typeFit: ['SSGT', 'SESD', 'BSST', 'BESD'],
    field: 'Business Analysis',
    description: 'Drive digital transformation initiatives across government-linked corporations in Malaysia.',
  },
  {
    id: 'sizebook-media',
    title: 'Video Streaming Engineer',
    company: 'Sizebook',
    salaryMin: 6500,
    salaryMax: 12000,
    demand: 'Competitive',
    skillsRequired: ['HLS', 'FFmpeg', 'CDN', 'Node.js', 'Video Codecs'],
    skillsUser: ['Web Development', 'Computer Networks', 'Operating Systems', 'Software Engineering'],
    typeFit: ['BECT', 'BSST', 'BESD', 'BEST'],
    field: 'Software Engineering',
    description: 'Build low-latency video streaming infrastructure for Sizebook\'s creator platform.',
  },
];

export function matchJobsToType(type: string, userSkills: string[], userCourses: string[]): Job[] {
  const scored = jobs.map(job => {
    let match = 0;
    // Type affinity
    if (job.typeFit.includes(type)) match += 40;
    // Skill overlap
    const userSkillsLower = [...userSkills, ...userCourses].map(s => s.toLowerCase());
    const overlap = job.skillsRequired.filter(skill =>
      userSkillsLower.some(us => us.includes(skill.toLowerCase()) || skill.toLowerCase().includes(us))
    ).length;
    const skillScore = Math.round((overlap / job.skillsRequired.length) * 60);
    return { job, score: match + skillScore, overlap };
  });
  return scored.sort((a, b) => b.score - a.score).slice(0, 3).map(s => s.job);
}

// ─── Job Matching Interface & Scoring ───────────────────────────────────────

export interface JobMatch {
  job: Job;
  totalScore: number;       // 0-100
  personalityScore: number; // 0-40
  skillScore: number;       // 0-30
  courseScore: number;      // 0-30
  personalityFit: boolean;    // true if job.typeFit includes their type
  skillsCovered: string[];
  skillsMissing: string[];
  coursesCovered: string[];
  coursesMissing: string[];
}

/**
 * Fuzzy match: true if skill is found as substring in list item OR vice versa.
 */
function fuzzyMatch(skill: string, list: string[]): boolean {
  const skillLower = skill.toLowerCase();
  return list.some(s => s.toLowerCase().includes(skillLower) || skillLower.includes(s.toLowerCase()));
}

/**
 * Returns ALL jobs scored and ranked by total match score.
 * Scoring breakdown (max 100):
 *   - Personality fit: +40 if job.typeFit includes type, else 0
 *   - Skill overlap (30pts): (overlap / job.skillsRequired.length) * 30
 *     overlap = skillsRequired matched by userSkills OR userCourses
 *   - Course coverage (30pts): (courseOverlap / job.skillsRequired.length) * 30
 *     courseOverlap = skillsRequired matched ONLY by userCourses
 */
export function calculateJobMatches(
  type: string,
  userSkills: string[],
  userCourses: string[]
): JobMatch[] {
  const allUserItems = [...userSkills, ...userCourses];

  return jobs.map(job => {
    // Personality score (binary 40 or 0)
    const personalityFit = job.typeFit.includes(type);
    const personalityScore = personalityFit ? 40 : 0;

    // Determine which skills are covered by userSkills+userCourses (skill match)
    const skillsCovered: string[] = [];
    const skillsMissing: string[] = [];
    for (const skill of job.skillsRequired) {
      if (fuzzyMatch(skill, allUserItems)) {
        skillsCovered.push(skill);
      } else {
        skillsMissing.push(skill);
      }
    }

    // Determine which skills are covered ONLY by userCourses (course match)
    const coursesCovered: string[] = [];
    const coursesMissing: string[] = [];
    for (const skill of job.skillsRequired) {
      if (fuzzyMatch(skill, userCourses)) {
        coursesCovered.push(skill);
      } else {
        coursesMissing.push(skill);
      }
    }

    const skillScore = Math.round((skillsCovered.length / job.skillsRequired.length) * 30);
    const courseScore = Math.round((coursesCovered.length / job.skillsRequired.length) * 30);
    const totalScore = personalityScore + skillScore + courseScore;

    return {
      job,
      totalScore,
      personalityScore,
      skillScore,
      courseScore,
      personalityFit,
      skillsCovered,
      skillsMissing,
      coursesCovered,
      coursesMissing,
    };
  }).sort((a, b) => b.totalScore - a.totalScore);
}
